Repository osu-tournament-rating/otr-processor, pull requests merged in 2024-05, with the labels that each got.

#40 Change (some of) tests to not use direct float comparisons
  src/api/mod.rs
  src/main.rs
  src/model/mod.rs
Labels: size/M

#38 Add `GameWinRecord` support
  src/api/api_structs.rs
  src/api/mod.rs
  src/main.rs
  src/model/constants.rs
  src/model/mod.rs
Labels: area:statistics, size/L

#39 Fix clippy issues & apply `cargo fmt` everywhere
  benches/calc_rating.rs
  benches/global_country_rank.rs
  src/model/mod.rs
  src/model/structures/processing.rs
Labels: type:code-quality, size/L

#43 Add a POST rating adjustments request
  .github/workflows/ci.yml
  src/api/mod.rs
Labels: size/M

#44 Fix decay adjustments
  src/model/decay.rs
  src/model/mod.rs
Labels: size/S

#45 Implement `GameWinRecord`, `MatchWinRecord`, and `PlayerMatchStats` generation
  Cargo.lock
  Cargo.toml
  src/api/api_structs.rs
  src/main.rs
  src/model/data_processing.rs
  src/model/mod.rs
  src/model/structures/match_type.rs
  src/model/structures/mod.rs
  src/model/structures/processing.rs
Labels: area:statistics, epic, size/XXL

#46 Implement numerous stats & upload to database
  src/api/api_structs.rs
  src/api/mod.rs
  src/main.rs
  src/model/mod.rs
  src/model/structures/processing.rs
  src/model/structures/team_type.rs
Labels: size/XL

#48 Adapt to changes from otr-api/#312, fix NaN bug, introduce new Match …
  benches/calc_rating.rs
  benches/global_country_rank.rs
  src/api/api_structs.rs
  src/api/mod.rs
  src/main.rs
  src/model/data_processing.rs
  src/model/decay.rs
  src/model/mod.rs
  src/model/recalc_helpers.rs
  src/model/structures/match_type.rs
  src/model/structures/match_verification_status.rs
  src/model/structures/mod.rs
  src/model/structures/player_rating.rs
  src/model/structures/processing.rs
  src/model/structures/ruleset.rs
  src/model/structures/team_type.rs
  src/utils/progress_utils.rs
  test_data/match_2v2.json
  test_data/owc_2023.json
Labels: area:api, size/XXL
