Repository osu-tournament-rating/otr-processor, pull requests merged in 2024-03, with the labels that each got.

#28 Use nightly toolchain in format stage of CI
  .github/workflows/ci.yml
Labels: size/XS

#29 Proposal: Add formatting settings
  rustfmt.toml
Labels: size/XS

#27 Bug fixes, tests for rating algorithm
  src/api/mod.rs
  src/main.rs
  src/model/decay.rs
  src/model/mod.rs
  src/model/structures/rating_calculation_result.rs
Labels: size/L

#32 fix ci and formatting warning
  .github/workflows/ci.yml
  rustfmt.toml
  src/api/api_structs.rs
  src/api/mod.rs
  src/env.rs
  src/main.rs
  src/model/constants.rs
  src/model/data_processing.rs
  src/model/decay.rs
  src/model/mod.rs
  src/model/structures/match_cost.rs
  src/model/structures/mod.rs
  src/model/structures/mode.rs
  src/model/structures/player_rating.rs
  src/model/structures/rating_calculation_result.rs
  src/utils/mod.rs
  src/utils/progress_utils.rs
Labels: size/L

#33 Use new oauth2 authorization method
  env_example
  src/api/api_structs.rs
  src/api/mod.rs
  src/main.rs
Labels: size/M

#34 Oauth2 token auto refresh logic
  Cargo.lock
  Cargo.toml
  src/api/api_structs.rs
  src/api/mod.rs
Labels: size/L
