Repository osu-tournament-rating/otr-processor, pull requests merged in 2024-06, with the labels that each got.

#55 Change all statics into consts
  src/model/constants.rs
  src/model/decay.rs
Labels: size/M

#54 Fix country ranking bugs
  benches/calc_rating.rs
  benches/global_country_rank.rs
  src/model/mod.rs
  src/model/structures/player_rating.rs
Labels: bug, area:statistics, size/L

#56 add release yml
  .github/release.yml
Labels: size/S

#57 skip missing players (prod issue)
  src/model/mod.rs
Labels: size/S

#58 Revert "skip missing players (prod issue)"
  src/model/mod.rs
Labels: size/S

#59 Remove unused calculate player adjustments function
  src/lib.rs
  src/model/mod.rs
Labels: type:code-quality, size/M

#60 Quality/readability conciseness improvements
  .gitignore
  src/model/mod.rs
Labels: size/M

#62 Add GPL 3 license
  LICENSE.txt
Labels: size/XL
