Repository osu-tournament-rating/otr-processor, pull requests merged in 2025-05, with the labels that each got.

#96 Fix unused fields in decay.rs and slightly improve docs
  src/model/decay.rs
Labels: size/S

#98 Updated sample match test and test description
  src/model/constants.rs
  src/model/otr_model.rs
Labels: size/L

#101 Fix bugs with player fetching and rating processing
  src/database/db.rs
  src/model/otr_model.rs
Labels: bug, size/L
