Repository osu-tournament-rating/otr-processor, pull requests merged in 2025-06, with the labels that each got.

#106 Use PostgreSQL `COPY` statement for bulk insert operations
  Cargo.lock
  Cargo.toml
  src/database/db.rs
Labels: bug, size/L

#108 Changes to initial rating and decay calculation
  src/model/constants.rs
  src/model/rating_utils.rs
Labels: size/M

#116 Add IGNORE_CONSTRAINTS env var
  .env.example
  src/args.rs
  src/database/db.rs
  src/utils/progress_utils.rs
  tests/common/mod.rs
  tests/database/crash_simulation_tests.rs
  tests/database/db_tests.rs
  tests/database/transaction_tests.rs
  tests/integration/main_flow_tests.rs
  tests/integration_tests.rs
Labels: size/L
